### ISSUE TITLE
一点小疑问

### ISSUE THREAD

**Issue by tinygrox** [RafertyLee/Kraken#4]
在 GitHub 找代码时偶然发现此项目，发现好像是国人弄的，就粗略看了一下整个项目，那么对于该项目的目标本人目前有一点疑问：

1. 是否涉嫌重复造轮子？
项目本身也说明了是基于 kRPC 而产生，先暂时撇开既懂编程又会玩坎巴拉的人数基数，那么对于【懂编程】的这部分目标玩家来说，此项目的定位是什么呢？是封装了一堆调用 kRPC 方法的简化版 kRPC 吗？
玩家是需要编写一个完整的程序还是说像 kOS 那样只需编写相对来说简单的脚本或是部分代码？如果是编写完整的程序那么此项目是完全独立于kRPC（无需再安装kRPC）还是仍需 kRPC 作为前置，在成果上类似于一个KRPC 的子 Mod 比如 [KRPC MechJeb](https://github.com/Genhis/KRPC.MechJeb)？

同时为何此项目不采用直接发布可运行的 kPRC 代码，将游戏内入轨、对接等操作模块化形成一个一个的方法，然后附上相应的注释和调用示例，也就是计划中的【编写算法库】，而是要重新花费大量时间去构造一个类似新框架的东西？这是否有点重复造轮子的嫌疑？

先声明本人并无任何恶意，本人知道此项目的目标是面向那些【想通过自己的写的程序来玩游戏】的玩家群体，同时也知道该项目还处于早期萌芽阶段。

**Comment by RafertyLee** [comment]
### 非常抱歉，此前并没有注意到有新增的issue。现在我将对您的疑问一一作出答复：
- 我们知道编写kRPC程序对物理、数学和控制的基础有一定要求，要编写出较完美的程序更是困难。而我们的目标则是使KSP玩家在初步了解编程之后便能实现一定程度上的自动化，而免去大量繁杂基础知识的学习。我们不是提供简化的kRPC。
- 项目一直坚持编写完整程序，支持主流编程语言。
- 我们会对原来的kRPC做出改进，与此同时保留对原kRPC的兼容，并将此作为项目前置
- 像kRPC MechJeb，但是更加高级。我们会自动生成参数，而非请求参数。我们会依靠内置物理模型直接计算，而不像MJ会依靠游戏内工具。
- 作为开源项目，自然可以直接于仓库中查询操作的模块化代码。但是，为了简化编程与物理计算，每个方法会需要大量参数。我们选择动态链接库以方便跨语言和简化传参过程。
---
### 以上部分为项目目标，并不能保证短时间内完成。如果有不全之处，欢迎您继续提出您的疑问，同时欢迎您这样对KSP热爱的人加入我们的项目。

**Comment by tinygrox** [comment]
那我就先简单理解该项目是一个全新的类似于 kRPC MechJeb 的依赖于 kRPC 的一个 addon ，如果如此，那我就没问题了，个人由衷祝愿你们未来开发顺利，很高兴现在还能有人愿意将时间投入在 KSP 上。
😃
